apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.name }}-svc
  namespace: {{ .Release.Namespace }}
spec:
  selector:
    app: {{ .Values.name }}
{{- if .Values.service.ports }}
  ports:
{{ toYaml .Values.service.ports | indent 4 }}
{{- end }}
  type: "{{ .Values.service.type }}"
